### ISSUE TITLE
Some type cant display correctly

### ISSUE THREAD

**Issue by majiayu000** [fast-reflexes/better-react-mathjax#58] opened 2024-03-26 03:46 UTC
Some latex like `$12 - \frac{7}{11}$`.

If put this in mathjax, this can display, but cant here.
![image](https://github.com/fast-reflexes/better-react-mathjax/assets/19658300/ca97af66-480f-42a5-9390-18d1c3abb6bc)
![image](https://github.com/fast-reflexes/better-react-mathjax/assets/19658300/bd697844-8b6f-438a-b814-4504fa2a8207)

**Comment by fast-reflexes** [comment] 2024-03-26 06:49
I think you're just forgetting about escape characters in Javascript strings. When you want to output a `\` you have to add `\\` inside a string.

**Comment by majiayu000** [comment] 2024-03-26 07:09
![image](https://github.com/fast-reflexes/better-react-mathjax/assets/19658300/38333e32-2486-4305-8e2f-cc6ee540fabf)
Seems not a `\` question.

**Comment by fast-reflexes** [comment] 2024-03-26 07:35
Have you added `$` as a delimiter in your config? At least you're no longer getting `Math input error` so you also had a problem with escaping it seems.

**Comment by majiayu000** [comment] 2024-03-26 08:48
Thanks for your patients. After I using config, it worked. I did not see these configs.

**Comment by fast-reflexes** [comment] 2024-03-26 09:00
No problem :) Feel free to close this ticket if the problem is solved :)

**Comment by majiayu000** [comment] 2024-03-26 10:39
\frac{1}{2}
I meet another question. How can just display a latex without any `\\` or `(`.

Thank you!

**Comment by fast-reflexes** [comment] 2024-03-26 11:18
You can't. MathJax operates on delimiters. You can use manual typesetting and provide the string you want to typeset like

```js
          <MathJax
            renderMode={"pre"}
            typesettingOptions={{ fn: "tex2chtml" }}
            text={`x^4 = 100`}
          />
```
but I wouldn't recommend that.

**Comment by majiayu000** [comment] 2024-03-27 02:27
Ok, so the question is to discover the latex string. I will try, thank you again!

**Closed** 2024-03-27 02:28 UTC
