### ISSUE TITLE
MathJax.js:1 Uncaught (in promise) Error: Typesetting failed: Cannot read properties of null (reading 'contains')

### ISSUE THREAD

**Issue by Omer1Yuval1** [fast-reflexes/better-react-mathjax#57] opened 2024-03-02 15:32 UTC
This error seems to happen when the `key` attribute of the `<MathJax>` tag contains certain characters.

**Comment by fast-reflexes** [comment] 2024-03-02 19:08
This is impossible to troubleshoot without a reproducible sample showing where this error occurs, please provide one or close the ticket.

**Comment by fast-reflexes** [comment] 2024-03-04 16:10
Can you create a reproducible sample?

**Comment by fast-reflexes** [comment] 2024-03-07 10:39
Closing since not enough to work with, feel free to reopen when you can provide more info.

**Closed by fast-reflexes** 2024-03-07 10:39 UTC
