### ISSUE TITLE
it's making my pages so slow, any suggestions?

### ISSUE THREAD

**Issue by demonhunter3333** [fast-reflexes/better-react-mathjax#8] opened 2021-12-25 14:53 UTC
It's much slower than if I just include an external script in the HTML. Any suggestions?

**Comment by fast-reflexes** [comment] 2021-12-26 10:21
Hi there! Hmm.. there are too many unknown variables for me to even START looking in to this.

Could you provide a sandbox with a sample of how you're using the components and also let me know how you have measured time ... Is the difference so big so you don't even have to measure time? Hopefully, there is some way to improve things which would be nice to look into, but depending on the use case, it CAN be that using MathJax in React is slower than using it in a plain HTML / JS environment. After all, the biggest benefit of React is not that it improves speed of websites but instead that it provides an easy-to-use interface to managing and updating the DOM. Nonetheless, I don't think React being slow is typically a problem so hopefully, there is something else we can change.. either in how you use this library, or in the source code of this library. No matter which, I'd be glad to help out :)

**Comment by demonhunter3333** [comment] 2021-12-27 06:30
Hi, thanks for replying! And thanks for making this awesome tool!

Mine is a Next.js site.

Here's the deployment link with all 60 \<MathJax> components rendered on loading:
https://ah-nextjs-9qeepgcaq-chenbingyingsydney-gmailcom.vercel.app/c01-math
Visit the link with a phone, and open the Navbar, open "Browse Questions by Test", and click on any link thereunder, and my site will become so slow that it's barely usable.

Here's my temporary workaround, with each \<MathJax> component to be rendered manually:
https://ah-nextjs-6vrn11prf-chenbingyingsydney-gmailcom.vercel.app/c01-math
-- very fast.

The difference in performance is so palpable that I don't need an analytics tool.

I wrap the \<MathJaxContext> in _app.js:
![Screenshot 2021-12-27 at 2 21 07 PM](https://user-images.githubusercontent.com/43437154/147440906-d8e99032-a1e6-4586-8a14-2a0023f7d141.png)

... and \<MathJax> for each individual component where there is Latex (there are 60 of them on a page):
![Screenshot 2021-12-27 at 2 21 57 PM](https://user-images.githubusercontent.com/43437154/147440959-c120b37a-6c5c-40d1-9042-dcf4a17f8199.png)

**Comment by fast-reflexes** [comment] 2021-12-27 10:26
When you say that you have a temporary fix that renders each part manually, how do you accomplish this?

**Comment by demonhunter3333** [comment] 2021-12-27 10:42
> When you say that you have a temporary fix that renders each part manually, how do you accomplish this? 

I add a local Boolean state "showAns" for each component. As shown in the screenshot above:

showAns && \<MathJax> x + y \</MathJax>

**Comment by fast-reflexes** [comment] 2021-12-27 16:02
So you mean you Ok basically, you're only showing / typesetting one equation at the time with the last solution which results in acceptable performance.

Basically, when you have this many things to typeset, using individual `MathJax` components for each might not be optimal. Try to wrap the full table in a `MathJax` component, that should improve performance. Let me know if that works.

On a side note, it might be better to not show all that info at the same time, I'm not saying this to defend the library or anything since I think it should work anyways, but from a user perspective, it might be better to only show the current part since we can't look at multiple parts at the same time anyways. It might be beneficial also from an image perspective.

**Comment by fast-reflexes** [comment] 2022-01-02 16:45
Yeah so after some investigations, it turns out that running MathJax 120 times on small parts takes much longer than running it 1 time on a larger chunk of code containing all these 120 small portions (or in your case 60). This seems to be a property of MathJax so the general recommendation / workaround is to either typeset larger parts at the same time (like I recommended you to do) or simply come up with some other scheme where the requirement to use very many `MathJax` components at the same time is avoided (e.g. your own solution where you only typeset the currently shown exercise).

Will close this and make sure to add more info about this in the docs.

Thanks for pointing it out!

**Comment by pkra** [comment] 2022-01-02 21:17
> Yeah so after some investigations, it turns out that running MathJax 120 times on small parts takes much longer than running it 1 time on a larger chunk of code containing all these 120 small portions (or in your case 60). This seems to be a property of MathJax 

This has little to do with MathJax -- this is just a case of causing layout thrashing https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing

**Comment by fast-reflexes** [comment] 2022-01-03 09:19
@pkra thanks for your input, learnt a lot ... but what are you suggesting...

* We shouldn't use a layout like this at all (at a higher level)
* We shouldn't use the `MathJax` component like this (e.g. include more content in one component instead of using 120 different ones)
* There is something related to this that can be improved in `better-react-mathjax` (e.g. uses MathJax in an inappropriate way)
* There is something related to this that can be improved in MathJax

I tried doing this without `better-react-mathjax` and it still takes a lot of time.. so it seems to ME that the forced reflow (as suggested by my Chrome dev tools) is caused by code inside MathJax that forces the browser to continuously render at least one time every time typesetting is done. This suggests either that MathJax should not be used in this way (e.g. we should either typeset the whole page or add multiple elements to the same typesetting array instead of queuing them in the promise) or that the problem lies within MathJax (may be required for MathJax to function properly and suggests that MathJax should be used more wisely, queuing only a few typesetting operations at a time).

What do you think? :)

**Comment by pkra** [comment] 2022-01-03 12:48
Disclaimer: I don't work with react and I don't know better-react-mathjax - I'm just a former MathJax team member and follow interesting projects in this space. So please feel free to disregard this entirely.

>  if we supply all the elements in the typesetting array at once, it goes fast and is done in one go. 

That's the relevant point, I think. MathJax's default behavior will create the output for many equations and then update the DOM once; this avoids layout thrashing. I realize this kind of synchronization doesn't really align with how components usually work.

On the one hand, I suspect creating a custom MathJax adaptor (cf. https://github.com/mathjax/MathJax-src/tree/master/ts/adaptors) that can write to react's virtual dom might help in many situations. (MathJax's litedom adaptor is probably fairly close already.) 

On the other hand, writing MathJax output to the VDOM will increase the VDOM; that could negatively affect the entire application (e.g., VDOM diffing).

Of course there are also other ways to improve things, e.g., SSR and possible hydration.

I don't think there's an easy one-size-fits-all solution. This library helps a lot of developers - congratulations and thank you! - maybe it doesn't need to solve every use case.

**Comment by fast-reflexes** [comment] 2022-01-06 10:15
Thanks @pkra, for you input, really interesting and I appreciate it! I think for now, my action point will be documentation but there are definitely some interesting directions to take in the long run.

**Closed by fast-reflexes** 2022-01-06 10:15 UTC
Labels: documentation, help wanted
