### ISSUE TITLE
Error: Typesetting failed: Cannot read properties of null (reading 'contains')

### ISSUE THREAD

**Issue by sushilbalami** [fast-reflexes/better-react-mathjax#5] opened 2021-09-04 11:12 UTC
I have to load many many MathJax and when i used it on next js i got this error
**Error: Typesetting failed: Cannot read properties of null (reading 'contains')**

_so simply loops each question and calls this function my code:_

```
function decideQuestion(value) {
  if (value.includes("http://www.w3.org/1998/Math/MathML")) {
    return (
      <MathJaxContext>
        <MathJax>{parse(value)}</MathJax>
      </MathJaxContext>
    );
  } else {
    return parse(value);
  }
}

```

**Comment by fast-reflexes** [comment] 2021-09-04 12:30
Thanks for your question! 

First a general comment:

You shouldn't use the `MathJaxContext` inside a call like that. You should wrap the outermost component containing math or the entire app in a `MathJaxContext`. In your case, the problem is that if you have multiple calls to this function, there will be multiple `MathJaxContext`s, each and one presumably downloading a version of MathJax which is highly inefficient (you only need one MathJax to be downloaded). On top of this, the `MathJaxContext` should be a wrapper that survives the lifetime of the app without being replaced and rerendered every now and then. On different renders of your app, the `MathJaxContext` may get removed and then readded, over and over again, causing MathJax to be downloaded once for every render. This is obviously inefficient. So to sum up, try to wrap som larger portion of the app as said, (the entire app if needed) that doesn't rerender in a `MathJaxContext` and then use `MathJax` components wherever you want inside that component. The `MathJax` components can rerender, that's not a problem, but then they should have the `dynamic` property set..

Regarding your actual question. It looks like you're using MathML... MathML can't be added as a string to MathJax since MathML consists of DOM elements, as opposed to Latex and AsciiMath. Therefore you must convert the text representation of the MathML to DOM elements. In regular HTML this can be done by using `innerHTML` :

```
const div = document.createElement("div")
div.innerHTML = <MathML as a string here>
```

... whereupon the browser will turn the text into DOM elements. The corresponding property in React is `dangerouslySetInnerHTML` so the above example translates to:

```
<div dangerouslySetInnerHTML={{ __html: <MathML as string here> }}/>
```

Your example from the question (after having moved the `MathJaxContext` to a scope higher up in the hierarchy where it won't rerender and exist in multiple places) would then look like:

```
function decideQuestion(value) {
  if (value.includes("http://www.w3.org/1998/Math/MathML")) {
    return (
      <MathJax>
        <div dangerouslySetInnerHTML={{ __html: parse(value) }}/>
      </MathJax>
    );
  } else {
    return parse(value);
  }
}
```

However, even better for you would be to use some other functionality that is present, resulting in the following code:

```
function decideQuestion(value) {
  if (value.includes("http://www.w3.org/1998/Math/MathML")) {
    return (
      <MathJax 
        renderMode={"pre"} 
        text={parse(value)}
        typesettingOptions={{ fn: "mathml2chtml" }}
      />
    );
  } else {
    return parse(value);
  }
}
```

I prepared a basic sandbox for you: https://codesandbox.io/s/user-example-8-el6po

If you have some other problems or something that doesn't work, try to post a sandbox showing the error to make it easier to help you.

**Comment by sushilbalami** [comment] 2021-09-04 15:23
i have string like this
```
The slope of line <math xmlns="http://www.w3.org/1998/Math/MathML">
					  <mrow>
					    <mfrac>
					      <mi>x</mi>
					      <mi>a</mi>
					    </mfrac>
					  </mrow>
					  <mo>+</mo>
					  <mrow>
					    <mfrac>
					      <mi>y</mi>
					      <mi>b</mi>
					    </mfrac>
					  </mrow>
					  <mo>=</mo>
					  <mn>1</mn>
					</math>
```

so when i did this on 

```
 <MathJax
        renderMode={"pre"}
        text={value}
        typesettingOptions={{ fn: "mathml2chtml" }}
      />
```

results this error

**_Error: Typesetting failed: MathML must consist of a single element_**

**Comment by sushilbalami** [comment] 2021-09-04 15:47
i figure out error it is due to frame motion animation ......
so  
https://codesandbox.io/s/competent-rhodes-cgnj1?file=/src/App.js
i saw that here is no error but i have been working out with frame motion animation so ...
i think conflict becomes there

**Comment by fast-reflexes** [comment] 2021-09-04 16:34
Yes I understand that it doesn't work when there is both text AND MathML. With `renderMode={"pre"}`, it expects ONLY MathML. But I realized now that your `parse` function returns DOM elements so then all is well... I don't see any problem in the sandbox... can't you show the error in a sandbox?

**Comment by sushilbalami** [comment] 2021-09-05 02:40
![image](https://user-images.githubusercontent.com/33893625/132113051-4e6d9bfd-7b5b-4b9f-9a15-b7a1e73b8d00.png)
I had set UUID() to key because I don't have any option...
the index is already full an option doesn't have any ids so I have to put UUID() on key if I remove it UUID() on key error solves any reason behind 
you can look again now you can see an error
https://codesandbox.io/s/competent-rhodes-cgnj1?file=/src/App.js

**Comment by fast-reflexes** [comment] 2021-09-05 09:11
I think you have several problems in this code and before even addressing possible problems related to `better-react-mathjax` I think you need to fix other problems. 

The most obvious problem is how you supply keys to your components. I can't teach you everything about React and keys here but I will give you some advice. Keys should be **stable and coupled in a unique way with some specific instance of a component**. This means that a key should uniquely identify a specific instance of a component. For example using array index is not a good advice for a key since you can switch order of the items in an array and then the key (index) will identify a different instance of a component than last time, implying it does NOT uniquely identify the instance in question. In your case, you apply keys both for questions and for options. So what identifies a question in a unique way? Well, I assume you don't have multiple questions that look **exactly** the same so use the question itself as a key for the outer component where keys are applied (the `motion.div` component). For the options you have attempted to use `uuidv4()` which supplies a **NEW** unique identifier every time it is called. As you may know, React renders a virtual DOM as soon as it detects a change in props / state etc... and it then COMPARES this virtual DOM to the actual DOM and does replacements where necessary. In your case, on EVERY render you are supplying a NEW unique key for each option in each question. This means that React thinks that on every render, all the options of all questions are changed so it does the corresponding replacements in the real DOM. This is not what you're after since you want for example option number 1 of question number 1 to stay as it is as long as it is the same option (the key should indicate this). As a solution, instead use the question concatenated with the option index as a key (`question.question + idx`). As long as the order (index) of the options in the options array stays the same, this is a good choice of key. 

With these two changes, the code works as it should. This means that I will not look for a potential problem in `better-react-mathjax` :)

On a side note, you have set the single `ref` from `useInView` on all the `motion.div`'s corresponding to individual questions. I think this makes the `useInView` hook look for the moment when ALL the `motion.div`'s have been scrolled into view. I don't know the details of this library but this trigger seem to come first when you have scrolled all the way to the bottom, which I don't think is what you want. You should probably try to create a separate component for every question and use `useInView` inside this component (one `ref` per question instead of the same `ref` for all questions) instead so that each question shows up as soon as it is in view.

I created a [sandbox](https://codesandbox.io/s/charming-murdock-4h9gv) for you with my updates. I will close this thread now as it is not related to `better-react-mathjax`.

Good luck with your code!

**Closed by fast-reflexes** 2021-09-05 09:11 UTC
Labels: question
