### ISSUE TITLE
f.createElement is not a functin

### ISSUE THREAD

**Issue by rabbit16** [fast-reflexes/better-react-mathjax#63] opened 2024-05-17 08:18 UTC
When I import MathJaxContext to display math content and compile it using the command yarn build, an error stating 'f.createElement is not a function' appears on my page. However, the development environment works fine, and the error only occurs after building. I couldn't figure it out. What should I do?
![image](https://github.com/fast-reflexes/better-react-mathjax/assets/54702866/cc2c5529-c0de-488c-91de-daf00ec52645)
This is content component
```const renderText = useMemo(() => {
    const value = content || ''
    if (position === 'right') {
      return (
        <div ref={markdownBodyRef} className="markdown-body">
          <TeX math={value} />
        </div>
      )
    }
    const renderMdHtml = mdi.render(value)
    return (
      <div
        ref={markdownBodyRef}
        className="markdown-body"
        dangerouslySetInnerHTML={{
          __html: renderMdHtml
        }}
      />
    )
  }, [content, position]) 


{status === 'loading' ? <OpenAiLogo rotate /> : <MathJaxContext config={config}>
            <MathJax hideUntilTypeset={"first"}>
              {renderText}
              </MathJax>
              </MathJaxContext>}

**Comment by rabbit16** [comment] 2024-05-17 08:21
I used react frame.

**Comment by fast-reflexes** [comment] 2024-05-17 10:22
To begin with, you should never return the `MathJaxContext` conditionally like that and also in the middle of a component that it mounted and unmounted between renderings. Follow the instructions in the README : https://github.com/fast-reflexes/better-react-mathjax?tab=readme-ov-file#usage

If the problem persists, I can take another look.

**Comment by fast-reflexes** [comment] 2024-05-21 08:59
Closing this since no new input has been received, feel free to reopen if more info can be provided.

**Closed by fast-reflexes** 2024-05-21 08:59 UTC

**Comment by rabbit16** [comment] 2024-05-21 09:05
I've already resolved the issue by downgrading the version of Vite. The original version of Vite was 3.0, and after downgrading to version 2.0 and recompiling, everything worked fine.

**Comment by fast-reflexes** [comment] 2024-05-22 19:22
I can confirm that it works perfectly with Vite 5 both in development and in production. Haven't tried with Vite 3.
